### ISSUE TITLE
rename `release` branch to `next`

### ISSUE THREAD

**Issue by cball** [echobind/eb-scripts#18]
I feel like the name `release` is a little bit confusing, especially as a target branch. If we keep the approach where merging to master creates the release I think it might make more sense to name the default branch `next`. This way `next` would contain everything that will be in the next version.

Same concept different name. Thoughts?

**Comment by jsjoeio** [comment]
Makes sense to me! 

Whoever you want to do this (you or me), will you assign that issue to that person?

**Comment by jsjoeio** [comment]
We'll need to:

- [ ] create new branch `next` from `release`
- [ ] change default branch in Settings
- [ ] update CONTRIBUTING
- [ ] update branch protection settings

**Comment by jsjoeio** [comment]
I say once we get #24 and #26 merged in, let's tackle this.

**Comment by jsjoeio** [comment]
Now that I'm thinking about how others do it, I think this makes most sense:
- change `release` to `next` 
- make `master` the default. this way, users see it when they come to the repo and then the README and everything will be in sync with what they see on npm
- when we create a new release, we merge `next` into `master`

**Comment by jsjoeio** [comment]
Done via 773d8f9ccee252852f797433e09839bc370eff87
