### ISSUE TITLE
Ensure failures are surfaced properly

### ISSUE THREAD

**Issue by alvincrespo** [echobind/eb-scripts#27]
**Describe the bug**

https://github.com/echobind/eb-scripts/blob/release/.circleci/config.yml#L16

**Expected behavior**

We should not default to true if semantic-release fails.

**Additional context**

By defaulting to true, we might receive false positives and not be alerted that a release did not succeed on CI.

**Comment by jsjoeio** [comment]
I believe this is how it was set up by `semantic-release` when I first added it. Is the fix to remove the `|| true`? 

I wonder why they would put that in there?

**Comment by jsjoeio** [comment]
Closed via #30
