### ISSUE TITLE
React-Native-TypeScript Component creation import stories incorrect path

### ISSUE THREAD

**Issue by cmejet** [echobind/eb-scripts#44]
**Describe the bug**
When using eb-scripts to generate component it is importing incorrect path to `storybook/stories/index.ts`

```
import '../../src/components/TabIcon/TabIcon.stories';
import '../..//Users/jenn/_code/hoag/HoagMobile/src/components/Filter/Filter.stories';
```

**To Reproduce**

1. Run `eb-scripts generate react-native-typescript-component -p src/components -n` with component name.
2. Note successful injection of the story to `stories/index.ts` however the path is not correct 
3. See error "Unable to resolve module...."

**Expected behavior**

**Screenshots**
![Simulator Screen Shot - iPhone X - 2019-11-13 at 14 23 53](https://user-images.githubusercontent.com/7119624/68809689-4afcf280-0621-11ea-8d1f-7e07bc5cb123.png)

**Additional context**

**Comment by cmejet** [comment]
Would this be a good one to try contributing??

**Comment by jsjoeio** [comment]
@cmejet yes! This would be fantastic! If you want to tackle it, feel free to assign to yourself and go for it. I can help if needed 😄 Should be something you could knock out in less than an hour
