### ISSUE TITLE
Add linting to project

### ISSUE THREAD

**Issue by alvincrespo** [echobind/eb-scripts#9]
We should use our own eslint config: https://github.com/echobind/eslint-plugin-echobind

**Comment by jsjoeio** [comment]
Does this mean add linting for `eb-scripts` itself, or so that when users use `eb-scripts`, it includes our `eslintrc` for them, under the hood?

Or both?

**Comment by cball** [comment]
I'd vote for both.

**Comment by alvincrespo** [comment]
I'll separate out the implementation of including our eb-scripts in a developers configuration as a separate issue.

This one was specifically for eb-scripts itself.

**Comment by jsjoeio** [comment]
> I'll separate out the implementation of including our eb-scripts in a developers configuration as a separate issue.

@alvincrespo created #25

I'll pick up this one.
